annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Grafana
      url: https://github.com/grafana/grafana
    - name: Loki
      url: https://github.com/grafana/loki
    - name: Mimir
      url: https://github.com/grafana/mimir
    - name: Tempo
      url: https://github.com/grafana/tempo
apiVersion: v2
appVersion: ^7.3.9
dependencies:
- alias: grafana
  condition: grafana.enabled
  name: grafana
  repository: file://charts/grafana
  version: 7.3.12
- alias: loki
  condition: loki.enabled
  name: loki
  repository: file://charts/loki
  version: 6.9.0
- alias: mimir
  condition: mimir.enabled
  name: mimir-distributed
  repository: file://charts/mimir-distributed
  version: 5.7.0
- alias: tempo
  condition: tempo.enabled
  name: tempo-distributed
  repository: file://charts/tempo-distributed
  version: 1.42.2
- alias: grafana-oncall
  condition: grafana-oncall.enabled
  name: oncall
  repository: file://charts/oncall
  version: 1.7.2
- alias: otelcol
  condition: otelcol.enabled
  name: opentelemetry-collector
  repository: file://charts/opentelemetry-collector
  version: 0.133.0
description: Umbrella chart for a distributed Loki, Grafana, Tempo and Mimir stack
home: https://grafana.com/oss/
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
keywords:
- monitoring
- traces
- metrics
- logs
maintainers:
- name: timberhill
name: lgtm-distributed
sources:
- https://grafana.github.io/helm-charts
- https://github.com/grafana/grafana
- https://github.com/grafana/loki
- https://github.com/grafana/mimir
- https://github.com/grafana/tempo
type: application
version: 2.1.0
